version: '3'

services:
  web:
    image: ${REGISTRY}python:3.12-slim
    command: python -m http.server --bind 0.0.0.0 8080 
    ports:
      - "${PORT}:8080"
    environment:
      - REGISTRY=${REGISTRY}
      - LAUNCHER_VERSION=${LAUNCHER_VERSION}
      - DB_URL=postgresql://postgres:YzEJXbaU5qh4QuyBX8ee@db:5432/postgres
    working_dir: /etc

  db:
    image: ${REGISTRY}postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YzEJXbaU5qh4QuyBX8ee
      - POSTGRES_DB=postgres
    volumes:
      - ${VOLUME_DIR}/pgdata:/var/lib/postgresql/data